### ISSUE TITLE
Default Export is used always

### ISSUE THREAD

**Issue by fab1an** [kriszyp/eslint-plugin-auto-import#4]
I have a file `HashLocation.js`: 
```
export class HashLocation {
}
```

And I reference `HashLocation` somewhere else, what get's imported is:
`import HashLocation from "../src/core/HashLocation"`

This doesn't work though, as there's no default-export.

**Comment by kriszyp** [comment]
Do you have any suggestions for how you might want this to work? It seems pretty undesirable to actually load every module in the relative directory space, to test for exports. At least in our codebase, not only would this be disastrously slow, but couldn't even be done in node, since many of them expect a browser environment. There is an option for specifying individual top-level/non-relative modules that can safely be loaded to detect their exports, but the design of relative module search algorithm is to run fast by just checking directory contents. Or is non-default exports the standard pattern in your codebase, such that the `import` output could just be reformatted to specific pattern (like `import { <moduleName> } from '<modulePath>'`)?

**Comment by fab1an** [comment]
Is it possible to define the export manually in the config file then, without having to create a third file?

I'm thinking of something like.

```js
manualExport: 
    HashLocation: "src/util/HashLocation.js" 
}
```

You could also just `grep` the file, that should be fast.

**Comment by connebs** [comment]
Did you figure this out, @fab1an?

**Comment by fab1an** [comment]
No
